spring:
  application:
    name: sca-provider-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 30
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://jd:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
  cloud:
    nacos:
      discovery:
        server-addr: jd:8848
#        ip: 47.114.56.178

#    inetutils:
#      ignored-interfaces: eth.*
#      preferred-networks:
server:
  port: 10104
