spring:
  application:
    name: sca-consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: jd:8848
server:
  port: 10107

feign:
  client:
    config:
      default:  #服务名，填写default为所有服务
        connectTimeout: 3000  # 增加等待延时
        readTimeout: 12000

# 配置负载均衡，默通过ribbon实现，默认是轮询模式
sca-provider-service: # 单个服务写上服务名
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 随机规则
#   NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule # 轮询(默认)
#   NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule # 重试
#   NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule # 响应时间权重

# 多个服务不写服务名，但尝试未生效
#ribbon:
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule